const request = require('supertest');
const app = require('../../app');
const TrustTokenGenerator = require('../../components/TrustTokenGenerator');

// Mock AITextTransformer to simulate different AI service configurations
jest.mock('../../components/AITextTransformer', () => {
  return jest.fn().mockImplementation(() => ({
    transform: jest.fn().mockImplementation(async (text, type, options = {}) => {
      // Simulate realistic processing delay
      await new Promise((resolve) => setTimeout(resolve, 50));

      // Simulate different AI service responses based on configuration
      const baseMetadata = {
        processingTime: 100,
        tokens: {
          prompt: Math.ceil(text.length / 4),
          completion: 0,
          total: 0,
        },
        model: options.model || 'gpt-3.5-turbo',
        finish_reason: 'stop',
        provider: options.provider || 'openai',
      };

      switch (type) {
        case 'structure': {
          const structured = {
            title: `AI Processed Document (${baseMetadata.provider})`,
            summary: `Summary generated by ${baseMetadata.model}: ${text.slice(0, 30)}...`,
            content: text,
            key_points: [
              `Point 1 from ${baseMetadata.provider} processing`,
              `Point 2 with ${baseMetadata.model} enhancement`,
              `Point 3 demonstrating multi-provider compatibility`,
            ],
            metadata: {
              document_type: 'pdf',
              processing_method: 'ai_enhanced',
              ai_provider: baseMetadata.provider,
              ai_model: baseMetadata.model,
            },
          };
          baseMetadata.tokens.completion = JSON.stringify(structured).length / 4;
          baseMetadata.tokens.total = baseMetadata.tokens.prompt + baseMetadata.tokens.completion;
          return {
            text: JSON.stringify(structured),
            metadata: baseMetadata,
          };
        }

        case 'summarize': {
          const summary = `AI summary from ${baseMetadata.provider}/${baseMetadata.model}: ${text.slice(0, 40)}...`;
          baseMetadata.tokens.completion = summary.length / 4;
          baseMetadata.tokens.total = baseMetadata.tokens.prompt + baseMetadata.tokens.completion;
          return {
            text: summary,
            metadata: baseMetadata,
          };
        }

        case 'extract_entities': {
          const entities = {
            persons: ['John Doe', 'Jane Smith'],
            organizations: ['Example Corp'],
            locations: ['New York'],
            dates: ['2024-01-01'],
            provider: baseMetadata.provider,
            model: baseMetadata.model,
          };
          baseMetadata.tokens.completion = JSON.stringify(entities).length / 4;
          baseMetadata.tokens.total = baseMetadata.tokens.prompt + baseMetadata.tokens.completion;
          return {
            text: JSON.stringify(entities),
            metadata: baseMetadata,
          };
        }

        default: {
          return {
            text: text,
            metadata: {
              ...baseMetadata,
              processingTime: 30,
              tokens: { prompt: 1, completion: 1, total: 2 },
            },
          };
        }
      }
    }),
  }));
});

describe('PDF AI Multi-Provider Configuration Tests', () => {
  let trustTokenGenerator;
  let validTrustToken;

  beforeAll(() => {
    trustTokenGenerator = new TrustTokenGenerator();
    validTrustToken = trustTokenGenerator.generateToken('test content', 'test content', ['test'], {
      expirationHours: 1,
    });
  });

  describe('AI Service Configuration Compatibility', () => {
    const testPdfBuffer = Buffer.from(
      '%PDF-1.4\n1 0 obj\n<<\n/Type /Catalog\n/Pages 2 0 R\n>>\nendobj\n2 0 obj\n<<\n/Type /Pages\n/Kids [3 0 R]\n/Count 1\n>>\nendobj\n3 0 obj\n<<\n/Type /Page\n/Parent 2 0 R\n/MediaBox [0 0 612 792]\n/Contents 4 0 R\n>>\nendobj\n4 0 obj\n<<\n/Length 44\n>>\nstream\nBT\n/F1 12 Tf\n100 700 Td\n(Hello World) Tj\nET\nendstream\nendobj\nxref\n0 5\n0000000000 65535 f \n0000000009 00000 n \n0000000058 00000 n \n0000000115 00000 n \n0000000200 00000 n \ntrailer\n<<\n/Size 5\n/Root 1 0 R\n>>\nstartxref\n284\n%%EOF',
      'binary',
    );

    it('should work with default AI configuration', async () => {
      const response = await request(app)
        .post('/api/documents/upload?ai_transform=true')
        .set('x-trust-token', JSON.stringify(validTrustToken))
        .attach('pdf', testPdfBuffer, 'test.pdf');

      expect(response.status).toBe(200);
      expect(response.body.message).toBe('PDF uploaded and processed successfully');
      expect(response.body.processingMetadata).toBeDefined();
      expect(response.body.processingMetadata.model).toBe('gpt-3.5-turbo');
      expect(response.body.processingMetadata.provider).toBe('openai');
    });

    it('should handle AI processing with structured output', async () => {
      const response = await request(app)
        .post('/api/documents/upload?ai_transform=true')
        .set('x-trust-token', JSON.stringify(validTrustToken))
        .attach('pdf', testPdfBuffer, 'structure-test.pdf');

      expect(response.status).toBe(200);
      expect(response.body.sanitizedContent).toHaveProperty('title');
      expect(response.body.sanitizedContent).toHaveProperty('key_points');
      expect(response.body.sanitizedContent).toHaveProperty('summary');
      expect(response.body.processingMetadata.transformationType).toBe('ai_structure');
    });

    it('should support different AI models through configuration', async () => {
      // Mock different model configurations
      const AITextTransformer = require('../../components/AITextTransformer');

      // Test with GPT-4 configuration
      AITextTransformer.mockImplementation(() => ({
        transform: jest.fn().mockResolvedValue({
          text: 'GPT-4 processed content',
          metadata: {
            model: 'gpt-4',
            provider: 'openai',
            processingTime: 200,
            tokens: { prompt: 10, completion: 20, total: 30 },
          },
        }),
      }));

      const response = await request(app)
        .post('/api/documents/upload?ai_transform=true')
        .set('x-trust-token', JSON.stringify(validTrustToken))
        .attach('pdf', testPdfBuffer, 'gpt4-test.pdf');

      expect(response.status).toBe(200);
      expect(response.body.processingMetadata.model).toBe('gpt-4');
    });

    it('should handle AI service configuration errors gracefully', async () => {
      // Mock AI service failure
      const AITextTransformer = require('../../components/AITextTransformer');
      AITextTransformer.mockImplementation(() => ({
        transform: jest.fn().mockRejectedValue(new Error('AI service unavailable')),
      }));

      const response = await request(app)
        .post('/api/documents/upload?ai_transform=true')
        .set('x-trust-token', JSON.stringify(validTrustToken))
        .attach('pdf', testPdfBuffer, 'error-test.pdf');

      // Should still process but without AI enhancement
      expect(response.status).toBe(200);
      expect(response.body.message).toBe('PDF uploaded and processed successfully');
      expect(response.body.processingMetadata).toBeUndefined(); // No AI processing
    });

    it('should validate AI configuration parameters', async () => {
      // Test with invalid boolean value for ai_transform
      const response = await request(app)
        .post('/api/documents/upload?ai_transform=not_boolean')
        .set('x-trust-token', JSON.stringify(validTrustToken))
        .attach('pdf', testPdfBuffer, 'invalid-config.pdf');

      expect(response.status).toBe(400);
      expect(response.body.error).toContain('ai_transform');
    });

    it('should support AI processing toggling', async () => {
      // Test with AI disabled
      const noAiResponse = await request(app)
        .post('/api/documents/upload?ai_transform=false')
        .set('x-trust-token', JSON.stringify(validTrustToken))
        .attach('pdf', testPdfBuffer, 'no-ai-test.pdf');

      expect(noAiResponse.status).toBe(200);
      expect(noAiResponse.body.processingMetadata).toBeUndefined();

      // Test with AI enabled (default)
      const aiResponse = await request(app)
        .post('/api/documents/upload') // ai_transform defaults to true
        .set('x-trust-token', JSON.stringify(validTrustToken))
        .attach('pdf', testPdfBuffer, 'ai-enabled-test.pdf');

      expect(aiResponse.status).toBe(200);
      expect(aiResponse.body.processingMetadata).toBeDefined();
    });
  });
});
