name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
    - name: Install dependencies
      run: npm ci
    - name: Run lint
      run: npm run lint
    - name: Run tests
      run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t mcp-security:${{ github.sha }} .
    - name: Run container and health check
      run: |
        docker run -d --name app -p 3000:3000 mcp-security:${{ github.sha }}
        timeout 30 bash -c 'until curl -f http://localhost:3000/health; do sleep 1; done'
        docker stop app